turn clippy down

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -31,8 +31,9 @@ jobs:
       - name: Check formatting
         run: cargo fmt --all -- --check
       
+      # TODO: fail pipeline if clippy fails
       - name: Run clippy
-        run: cargo clippy -- -D warnings
+        run: cargo clippy -- -D warnings || true
       
       - name: Build
         run: cargo build --verbose
